### ISSUE TITLE
Should obey tab settings in the editor

### ISSUE THREAD

**Issue by JasonCubic** [Chakroun-Anas/turbo-console-log#32] opened 2019-01-16 18:31 UTC
my editor is set to use 2 spaces for the tab.  turbo console log inserts a real tab.
![image](https://user-images.githubusercontent.com/8921015/51270478-df52e600-1979-11e9-8327-ed9e68ce1244.png)

**Comment by adrigm** [comment] 2019-03-15 15:55
Same for me. Angular works with spaces.

**Comment by gabrielsclimaco** [comment] 2019-05-02 18:04
+1

**Comment by Chakroun-Anas** [comment] 2019-05-21 03:10
Duplicate of #59

**Closed** 2019-05-25 17:29 UTC
