### ISSUE TITLE
Multi Line issue for chained expressions with dot

### ISSUE THREAD

**Issue by Kalaschnik** [Chakroun-Anas/turbo-console-log#62] opened 2019-06-11 06:16 UTC
I’m using 1.2.23 and consider this code:
```
let myVariable = resources
  .filter(e => some filtering using e)
  .map(e => some mapping using e);
```

When selecting myVariable, hitting Ctrl+Alt+L it will insert the console.log here:
```
let myVariable = resources
console.log() // :-1: 
  .filter(e => some filtering using e)
  .map(e => some mapping using e);
```

yet, it should appear here:
```
let myVariable = resources
  .filter(e => some filtering using e)
  .map(e => some mapping using e);
console.log() // :+1: 
```

**Comment by Chakroun-Anas** [comment] 2019-06-27 14:39
Hello,

Sorry for the delay, i have just pushed a new version (1.2.24) that deals with this, please verify and share with me your feedback so we can close the issue.

Thank you so much.

**Comment by Kalaschnik** [comment] 2019-06-29 15:30
This changes might introduce another bug. The console.log is not set directly after the line. Instead it seems somehow random, see the gif:
![Peek 2019-06-29 17-27](https://user-images.githubusercontent.com/9831678/60386297-711b5f00-9a93-11e9-9a0b-2d10f27f400f.gif)

**Comment by germanfleitas** [comment] 2019-07-03 19:41
Hello, same issue here as @Kalaschnik. Some time it put the log even outside the function.

Turbo Console Log: `v1.2.25`
VS Code: `v1.36.0`
SO: `Windows 10`

Thanks!

**Comment by Chakroun-Anas** [comment] 2019-07-03 19:57
Hello,

I have made a real quick fix (it took me 5 minutes xD), i'm not sure if it cover all the cases so please test again and give me your feedback.

I promise that i will go back to this once i have more time.

Thanks and sorry for any inconvenience.

**Comment by germanfleitas** [comment] 2019-07-04 13:55
Thanks for the very quick feedback and sorry for my delayed response. I try it and it seems that it's working as expected now! But I guess the issue pointed by @Kalaschnik is still there.

Thanks!

**Comment by germanfleitas** [comment] 2019-07-05 15:26
Hi! Using the new version today I found that the error still happen, same system conditions:
![tcl_out_of_bounds](https://user-images.githubusercontent.com/43961673/60732263-f4b7ce80-9f1f-11e9-9eee-eb3b2458dbbc.gif)

Thanks!

**Comment by Chakroun-Anas** [comment] 2019-08-09 09:43
Hi @germanfleitas @Kalaschnik,

I have just pushed a fix, would you please test again and give me your feedback

Thx

**Comment by germanfleitas** [comment] 2019-08-10 16:21
Hi @Chakroun-Anas,
Sorry for the late response. I was testing and it seems that it works as intended!
Thanks!

**Closed** 2019-08-12 08:40 UTC
